const path = require('path')
// const fs = require('fs')
// const localPath = path.resolve('./lodash测试')
// console.log(path.join(__dirname, '/a/b/c'))
// console.log(path.extname(path.resolve('.vscode/launch.json')))
// path.join('')
console.log(path.resolve())